name: ramp-brainage-siterm
channels:
  - conda-forge
dependencies:
  - click<8.1.0
  - scipy
  - numpy
  - nibabel
  - pandas>=0.21
  - scikit-learn>=0.19
  - nilearn
  - matplotlib
  - seaborn
  - jupyter
  - progressbar2
  - pytorch
  - pip:
    - ramp-workflow
